#!/bin/bash
cat >/haproxy.cfg <<EOF
global
  daemon
  maxconn 256

defaults
  mode tcp
  timeout connect 5000ms
  timeout client 50000ms
  timeout server 50000ms

listen admin
  bind *:$1
  stats enable

frontend hamba-in
  bind *:$2
  default_backend hamba-out

backend hamba-out
EOF

shift
while [ "$2" ]; do
    echo "  server $2-$1 $2:$1 maxconn 32 " >> /haproxy.cfg
    shift
    shift
done
exec haproxy -f /haproxy.cfg -d
